---
title: "datafestproject"
output: html_document
Authors: "Hayden Lau, Isabel Garfinkel, Tiana Horace, Braden Hammond"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, 
                      message = FALSE, warning = FALSE,
                      fig.height=6, fig.width = 9, fig.align = "center")
```

# Library

```{r}
library(tidyverse)
```


# Data
```{r data}
Amazon_6M <- read_csv("data/Amazon 6M.csv")
AMC_6M <- read_csv("data/AMC 6M.csv")
Apple_6M <- read_csv("data/Apple 6M.csv")
ATT_HBO_6M <- read_csv("data/AT&T (HBO) 6M.csv")
Cinemark_6M <- read_csv("data/Cinemark 6M.csv")
Dish_6M <- read_csv("data/Dish 6M.csv")
Disney_6M <- read_csv("data/Disney 6M.csv")
Google_Class_A_6M <- read_csv("data/Google Class A 6M.csv")
Netflix_6M <- read_csv("data/Netflix 6M.csv")
Roku_6M <- read_csv("data/Roku 6M.csv")
global_cases <- read_csv("data/total-cases-covid-19.csv")
```

```{r}
entertainment_stocks<-Amazon_6M %>% 
  select(Date,Amazon_Close=`Close/Last`) %>% 
  mutate(AMC_Close = AMC_6M$`Close/Last`,
         Apple_Close = Apple_6M$`Close/Last`,
         ATT_Close = ATT_HBO_6M$`Close/Last`,
         Cinemark_Close = Cinemark_6M$`Close/Last`,
         Dish_Close = Dish_6M$`Close/Last`,
         Disney_Close = Disney_6M$`Close/Last`,
         Google_Close = Google_Class_A_6M$`Close/Last`,
         Netflix_Close = Netflix_6M$`Close/Last`,
         Roku_Close = Roku_6M$`Close/Last`)
US_cases<-global_cases %>% 
  filter(Entity=="United States")
global_cases<-global_cases %>% 
  filter(Entity=="World")
entertainment_stocks<-entertainment_stocks %>% 
  mutate(Date = as.Date(Date, format="%m/%d/%Y"))
global_cases<-global_cases %>% 
  mutate(Date = as.Date(Date, format = "%B %d, %Y")) %>% 
  select(Date, Global_Cases = `Total confirmed cases of COVID-19 (cases)`)
US_cases<-US_cases %>% 
  mutate(Date = as.Date(Date, format = "%B %d, %Y")) %>% 
  select(Date, US_Cases = `Total confirmed cases of COVID-19 (cases)`)
temp<-left_join(global_cases, US_cases, by = "Date")
stocks_cases<-full_join(entertainment_stocks, temp, by = "Date") %>% 
  arrange(Date)
stocks_cases$Amazon_Close<-as.numeric(gsub('[$]', '', stocks_cases$Amazon_Close))
stocks_cases$AMC_Close<-as.numeric(gsub('[$]', '', stocks_cases$AMC_Close))
stocks_cases$Apple_Close<-as.numeric(gsub('[$]', '', stocks_cases$Apple_Close))
stocks_cases$ATT_Close<-as.numeric(gsub('[$]', '', stocks_cases$ATT_Close))
stocks_cases$Cinemark_Close<-as.numeric(gsub('[$]', '', stocks_cases$Cinemark_Close))
stocks_cases$Dish_Close<-as.numeric(gsub('[$]', '', stocks_cases$Dish_Close))
stocks_cases$Disney_Close<-as.numeric(gsub('[$]', '', stocks_cases$Disney_Close))
stocks_cases$Google_Close<-as.numeric(gsub('[$]', '', stocks_cases$Google_Close))
stocks_cases$Netflix_Close<-as.numeric(gsub('[$]', '', stocks_cases$Netflix_Close))
stocks_cases$Roku_Close<-as.numeric(gsub('[$]', '', stocks_cases$Roku_Close))
```

# Visualizations

```{r}
# stocks_cases %>% 
#   filter(!is.na(Apple_Close)) %>% 
#   ggplot(aes(x=Date))+
#   geom_point(aes(y=Apple_Close),color="red")+
#   geom_point(aes(y=ATT_Close), color="blue")
par(mar=c(5, 4, 4, 6) + 0.1, pch = 16)
plot(x = stocks_cases$Date, y = stocks_cases$Global_Cases, type = "p", col = "black",axes=TRUE, frame.plot=TRUE, xlab="", ylab="")
mtext("Global Cases",side=2,line=2.5)
par(new=TRUE)
plot(x = stocks_cases$Date, y = stocks_cases$Apple_Close, type = "p", col = "red",axes=FALSE, frame.plot=TRUE, xlab="", ylab="")
mtext("Apple Close Price",side=4,col="red",line=4) 
axis(4, col="red",col.axis="red")

plot(x = stocks_cases$Date, y = stocks_cases$Global_Cases, type = "p", col = "black",axes=TRUE, frame.plot=TRUE, xlab="", ylab="")
mtext("Global Cases",side=2,line=2.5)
par(new=TRUE)
plot(x = stocks_cases$Date, y = stocks_cases$ATT_Close, type = "p", col = "red",axes=FALSE, frame.plot=TRUE, xlab="", ylab="")
mtext("AT&T Close Price",side=4,col="red",line=4) 
axis(4, col="red",col.axis="red")

plot(x = stocks_cases$Date, y = stocks_cases$Global_Cases, type = "p", col = "black",axes=TRUE, frame.plot=TRUE, xlab="", ylab="")
mtext("Global Cases",side=2,line=2.5)
par(new=TRUE)
plot(x = stocks_cases$Date, y = stocks_cases$Amazon_Close, type = "p", col = "red",axes=FALSE, frame.plot=TRUE, xlab="", ylab="")
mtext("Amazon Close Price",side=4,col="red",line=4) 
axis(4, col="red",col.axis="red")

plot(x = stocks_cases$Date, y = stocks_cases$Global_Cases, type = "p", col = "black",axes=TRUE, frame.plot=TRUE, xlab="", ylab="")
mtext("Global Cases",side=2,line=2.5)
par(new=TRUE)
plot(x = stocks_cases$Date, y = stocks_cases$Netflix_Close, type = "p", col = "red",axes=FALSE, frame.plot=TRUE, xlab="", ylab="")
mtext("Netflix Close Price",side=4,col="red",line=4) 
axis(4, col="red",col.axis="red")

plot(x = stocks_cases$Date, y = stocks_cases$Global_Cases, type = "p", col = "black",axes=TRUE, frame.plot=TRUE, xlab="", ylab="")
mtext("Global Cases",side=2,line=2.5)
par(new=TRUE)
plot(x = stocks_cases$Date, y = stocks_cases$Disney_Close, type = "p", col = "red",axes=FALSE, frame.plot=TRUE, xlab="", ylab="")
mtext("Disney Close Price",side=4,col="red",line=4) 
axis(4, col="red",col.axis="red")

plot(x = stocks_cases$Date, y = stocks_cases$Global_Cases, type = "p", col = "black",axes=TRUE, frame.plot=TRUE, xlab="", ylab="")
mtext("Global Cases",side=2,line=2.5)
par(new=TRUE)
plot(x = stocks_cases$Date, y = stocks_cases$AMC_Close, type = "p", col = "red",axes=FALSE, frame.plot=TRUE, xlab="", ylab="")
mtext("AMC Close Price",side=4,col="red",line=4) 
axis(4, col="red",col.axis="red")

plot(x = stocks_cases$Date, y = stocks_cases$Global_Cases, type = "p", col = "black",axes=TRUE, frame.plot=TRUE, xlab="", ylab="")
mtext("Global Cases",side=2,line=2.5)
par(new=TRUE)
plot(x = stocks_cases$Date, y = stocks_cases$Cinemark_Close, type = "p", col = "red",axes=FALSE, frame.plot=TRUE, xlab="", ylab="")
mtext("Cinemark Close Price",side=4,col="red",line=4) 
axis(4, col="red",col.axis="red")

plot(x = stocks_cases$Date, y = stocks_cases$Global_Cases, type = "p", col = "black",axes=TRUE, frame.plot=TRUE, xlab="", ylab="")
mtext("Global Cases",side=2,line=2.5)
par(new=TRUE)
plot(x = stocks_cases$Date, y = stocks_cases$Dish_Close, type = "p", col = "red",axes=FALSE, frame.plot=TRUE, xlab="", ylab="")
mtext("Dish Close Price",side=4,col="red",line=4) 
axis(4, col="red",col.axis="red")

plot(x = stocks_cases$Date, y = stocks_cases$Global_Cases, type = "p", col = "black",axes=TRUE, frame.plot=TRUE, xlab="", ylab="")
mtext("Global Cases",side=2,line=2.5)
par(new=TRUE)
plot(x = stocks_cases$Date, y = stocks_cases$Google_Close, type = "p", col = "red",axes=FALSE, frame.plot=TRUE, xlab="", ylab="")
mtext("Google Close Price",side=4,col="red",line=4) 
axis(4, col="red",col.axis="red")

plot(x = stocks_cases$Date, y = stocks_cases$Global_Cases, type = "p", col = "black",axes=TRUE, frame.plot=TRUE, xlab="", ylab="")
mtext("Global Cases",side=2,line=2.5)
par(new=TRUE)
plot(x = stocks_cases$Date, y = stocks_cases$Roku_Close, type = "p", col = "red",axes=FALSE, frame.plot=TRUE, xlab="", ylab="")
mtext("Roku Close Price",side=4,col="red",line=4) 
axis(4, col="red",col.axis="red")
```

